from __future__ import annotations

import contextlib
import os
import shlex
import sys
from pathlib import Path

import click

from ..utils import safe_echo

_MARKER = "Generated by gc setup gh-proxy"


def gh_proxy_dir() -> Path:
    override = os.environ.get("GC_GH_PROXY_DIR")
    if override:
        return Path(override).expanduser()
    if os.name == "nt":
        root = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
        return root / "gc" / "gh-proxy"
    return Path.home() / ".local" / "share" / "gc" / "gh-proxy"


def _shim_path(directory: Path) -> Path:
    return directory / ("gh.cmd" if os.name == "nt" else "gh")


def _shim_content() -> str:
    if os.name == "nt":
        return (
            f"@rem {_MARKER}\r\n"
            "@echo off\r\n"
            'set "GC_GH_SHIM=%~f0"\r\n'
            f'"{sys.executable}" -m gitcode_cli.gh_proxy %*\r\n'
            "exit /b %ERRORLEVEL%\r\n"
        )
    python = shlex.quote(sys.executable)
    return (
        f"#!/bin/sh\n# {_MARKER}\n"
        'GC_GH_SHIM="$0"\nexport GC_GH_SHIM\n'
        f'exec {python} -m gitcode_cli.gh_proxy "$@"\n'
    )


def install_gh_proxy(directory: Path) -> Path:
    shim = _shim_path(directory)
    if shim.exists() and _MARKER not in shim.read_text(encoding="utf-8", errors="replace"):
        raise click.ClickException(f"Refusing to overwrite unmanaged file: {shim}")
    directory.mkdir(parents=True, exist_ok=True)
    shim.write_text(_shim_content(), encoding="utf-8", newline="")
    if os.name != "nt":
        shim.chmod(0o755)
    return shim


def uninstall_gh_proxy(directory: Path) -> bool:
    shim = _shim_path(directory)
    if not shim.exists():
        return False
    if _MARKER not in shim.read_text(encoding="utf-8", errors="replace"):
        raise click.ClickException(f"Refusing to remove unmanaged file: {shim}")
    shim.unlink()
    with contextlib.suppress(OSError):
        directory.rmdir()
    return True


@click.group("setup", help="Configure optional gc integrations.")
def setup_group() -> None:
    pass


@setup_group.command(  # type: ignore[attr-defined]
    "gh-proxy", help="Install an optional gh dispatcher for GitCode and GitHub repositories."
)
@click.option("--print-path", is_flag=True, help="Print the proxy directory without changing it.")
@click.option("--uninstall", is_flag=True, help="Remove the managed gh proxy.")
def gh_proxy_command(print_path: bool, uninstall: bool) -> None:
    if print_path and uninstall:
        raise click.ClickException("--print-path and --uninstall cannot be used together.")
    directory = gh_proxy_dir()
    if print_path:
        safe_echo(str(directory))
        return
    if uninstall:
        removed = uninstall_gh_proxy(directory)
        safe_echo(f"Removed gh proxy from {directory}." if removed else f"No gh proxy found in {directory}.")
        return

    shim = install_gh_proxy(directory)
    safe_echo(f"Installed gh proxy at {shim}.")
    safe_echo(f"Add {directory} before the native gh directory in PATH.")
