from __future__ import annotations

import contextlib
import json
import os
import shlex
import sys
from pathlib import Path

import click

from ..utils import safe_echo

_MARKER = "Generated by gc setup gh-proxy"
_SHELL_BLOCK_START = "# >>> gc gh-proxy >>>"
_SHELL_BLOCK_END = "# <<< gc gh-proxy <<<"
_OPENCODE_MARKER = "<!-- Generated by gc setup gh-proxy -->"


def gh_proxy_dir() -> Path:
    override = os.environ.get("GC_GH_PROXY_DIR")
    if override:
        return Path(override).expanduser()
    if os.name == "nt":
        root = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
        return root / "gc" / "gh-proxy"
    return Path.home() / ".local" / "share" / "gc" / "gh-proxy"


def _shim_path(directory: Path) -> Path:
    return directory / ("gh.cmd" if os.name == "nt" else "gh")


def _shim_content() -> str:
    if os.name == "nt":
        return (
            f"@rem {_MARKER}\r\n"
            "@echo off\r\n"
            'set "GC_GH_SHIM=%~f0"\r\n'
            f'"{sys.executable}" -m gitcode_cli.gh_proxy %*\r\n'
            "exit /b %ERRORLEVEL%\r\n"
        )
    python = shlex.quote(sys.executable)
    return f'#!/bin/sh\n# {_MARKER}\nGC_GH_SHIM="$0"\nexport GC_GH_SHIM\nexec {python} -m gitcode_cli.gh_proxy "$@"\n'


def shell_profile() -> Path:
    override = os.environ.get("GC_GH_SHELL_PROFILE")
    if override:
        return Path(override).expanduser()
    if os.name == "nt":
        return Path.home() / "Documents" / "PowerShell" / "Microsoft.PowerShell_profile.ps1"
    shell = Path(os.environ.get("SHELL", "")).name
    if shell == "zsh":
        return Path.home() / ".zshenv"
    if shell == "bash":
        return Path.home() / ".bashrc"
    if shell == "fish":
        return Path.home() / ".config" / "fish" / "config.fish"
    raise click.ClickException("Unable to detect a supported shell profile; set GC_GH_SHELL_PROFILE.")


def _shell_block(directory: Path, profile: Path) -> str:
    if profile.name == "config.fish":
        path_line = f"set -gx PATH {shlex.quote(str(directory))} $PATH"
    elif profile.suffix == ".ps1":
        escaped = str(directory).replace("'", "''")
        path_line = f"$env:PATH = '{escaped};' + $env:PATH"
    else:
        path_line = f"export PATH={shlex.quote(str(directory))}:$PATH"
    return f"{_SHELL_BLOCK_START}\n{path_line}\n{_SHELL_BLOCK_END}"


def _replace_managed_block(path: Path, block: str | None) -> bool:
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    start = text.find(_SHELL_BLOCK_START)
    if start >= 0:
        end = text.find(_SHELL_BLOCK_END, start)
        if end < 0:
            raise click.ClickException(f"Malformed gc gh-proxy block in {path}")
        end += len(_SHELL_BLOCK_END)
        if end < len(text) and text[end] == "\n":
            end += 1
        text = text[:start] + text[end:]
    if block is not None:
        if text and not text.endswith("\n"):
            text += "\n"
        text += block + "\n"
    elif start < 0:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    return True


def configure_shell(directory: Path) -> Path:
    profile = shell_profile()
    _replace_managed_block(profile, _shell_block(directory, profile))
    return profile


def _opencode_config_path() -> Path:
    override = os.environ.get("GC_OPENCODE_CONFIG")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".config" / "opencode" / "opencode.json"


def _opencode_instructions() -> str:
    return (
        f"{_OPENCODE_MARKER}\n# gh Dispatcher\n\n"
        "- This machine installs `gh` as a repository-aware dispatcher for GitCode and GitHub. Use `gh` first for "
        "issue, pull-request, release, and repository operations on either host.\n"
        "- Never reject `gh` merely because a remote uses `gitcode.com`. Before claiming a host is unsupported, "
        "run `command -v gh` and `gh --version` in the target repository.\n"
        "- In a GitCode repository, `gh --version` identifies the pygitcode proxy, GitCode target, and `gc` backend. "
        "In a GitHub repository, the dispatcher delegates to native GitHub CLI.\n"
        "- Do not set `GH_HOST=gitcode.com`. For a non-origin GitCode repository, pass the host explicitly, for "
        "example `gh pr list -R gitcode.com/OWNER/REPO`.\n"
        "- Do not fall back to WebFetch, curl, or handwritten API requests until a direct `gh` command has been "
        "attempted and its failure output shows the dispatcher cannot satisfy the request.\n"
    )


def configure_opencode() -> tuple[Path, Path]:
    config_path = _opencode_config_path()
    instructions_path = config_path.parent / "gh-proxy-instructions.md"
    if instructions_path.exists() and _OPENCODE_MARKER not in instructions_path.read_text(encoding="utf-8"):
        raise click.ClickException(f"Refusing to overwrite unmanaged file: {instructions_path}")

    if config_path.exists():
        try:
            loaded_config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise click.ClickException(f"Invalid OpenCode config: {config_path}") from exc
        if not isinstance(loaded_config, dict):
            raise click.ClickException(f"OpenCode config must be a JSON object: {config_path}")
        config: dict[str, object] = loaded_config
    else:
        config = {"$schema": "https://opencode.ai/config.json"}
    raw_instructions = config.get("instructions")
    if raw_instructions is None:
        instructions: list[str] = []
        config["instructions"] = instructions
    elif isinstance(raw_instructions, list) and all(isinstance(item, str) for item in raw_instructions):
        instructions = raw_instructions
    else:
        raise click.ClickException(f"OpenCode instructions must be a string array: {config_path}")
    instruction_ref = str(instructions_path)
    if instruction_ref not in instructions:
        instructions.append(instruction_ref)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w", encoding="utf-8", newline="") as handle:
        handle.write(json.dumps(config, indent=2) + "\n")
    with open(instructions_path, "w", encoding="utf-8", newline="") as handle:
        handle.write(_opencode_instructions())
    return config_path, instructions_path


def uninstall_managed_configuration() -> tuple[Path | None, Path | None]:
    try:
        profile = shell_profile()
    except click.ClickException:
        profile = None
    removed_profile = profile if profile and _replace_managed_block(profile, None) else None

    config_path = _opencode_config_path()
    instructions_path = config_path.parent / "gh-proxy-instructions.md"
    removed_instructions: Path | None = None
    if instructions_path.exists() and _OPENCODE_MARKER in instructions_path.read_text(encoding="utf-8"):
        instructions_path.unlink()
        removed_instructions = instructions_path
    if config_path.exists():
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise click.ClickException(f"Invalid OpenCode config: {config_path}") from exc
        instructions = config.get("instructions")
        if isinstance(instructions, list) and str(instructions_path) in instructions:
            config["instructions"] = [item for item in instructions if item != str(instructions_path)]
            with open(config_path, "w", encoding="utf-8", newline="") as handle:
                handle.write(json.dumps(config, indent=2) + "\n")
    return removed_profile, removed_instructions


def install_gh_proxy(directory: Path) -> Path:
    shim = _shim_path(directory)
    if shim.exists() and _MARKER not in shim.read_text(encoding="utf-8", errors="replace"):
        raise click.ClickException(f"Refusing to overwrite unmanaged file: {shim}")
    directory.mkdir(parents=True, exist_ok=True)
    with open(shim, "w", encoding="utf-8", newline="") as handle:
        handle.write(_shim_content())
    if os.name != "nt":
        shim.chmod(0o755)
    return shim


def uninstall_gh_proxy(directory: Path) -> bool:
    shim = _shim_path(directory)
    if not shim.exists():
        return False
    if _MARKER not in shim.read_text(encoding="utf-8", errors="replace"):
        raise click.ClickException(f"Refusing to remove unmanaged file: {shim}")
    shim.unlink()
    with contextlib.suppress(OSError):
        directory.rmdir()
    return True


@click.group("setup", help="Configure optional gc integrations.")
def setup_group() -> None:
    pass


@setup_group.command(  # type: ignore[attr-defined]
    "gh-proxy", help="Install an optional gh dispatcher for GitCode and GitHub repositories."
)
@click.option("--print-path", is_flag=True, help="Print the proxy directory without changing it.")
@click.option("--uninstall", is_flag=True, help="Remove the managed gh proxy.")
@click.option("--configure", is_flag=True, help="Also configure the shell PATH and OpenCode instructions.")
def gh_proxy_command(print_path: bool, uninstall: bool, configure: bool) -> None:
    if sum((print_path, uninstall, configure)) > 1:
        raise click.ClickException("--print-path, --uninstall, and --configure cannot be used together.")
    directory = gh_proxy_dir()
    if print_path:
        safe_echo(str(directory))
        return
    if uninstall:
        removed_profile, removed_instructions = uninstall_managed_configuration()
        removed = uninstall_gh_proxy(directory)
        safe_echo(f"Removed gh proxy from {directory}." if removed else f"No gh proxy found in {directory}.")
        if removed_profile:
            safe_echo(f"Removed managed PATH block from {removed_profile}.")
        if removed_instructions:
            safe_echo(f"Removed managed OpenCode instructions from {removed_instructions}.")
        return

    shim = install_gh_proxy(directory)
    safe_echo(f"Installed gh proxy at {shim}.")
    if configure:
        profile = configure_shell(directory)
        config_path, instructions_path = configure_opencode()
        safe_echo(f"Configured PATH in {profile}.")
        safe_echo(f"Registered OpenCode instructions in {config_path} via {instructions_path}.")
        safe_echo("Restart OpenCode for the instructions to take effect.")
    else:
        safe_echo(f"Add {directory} before the native gh directory in PATH.")
        safe_echo("Run `gc setup gh-proxy --configure` to configure the shell and OpenCode automatically.")
