"""Registry entries — declarative gh-compatibility status.

Each tuple is ``(command, flag, status, note, **kwargs)`` where ``flag is None``
denotes a subcommand-level row. ``pending_key`` and ``unsupported_key`` link the
entry to runtime guards (enforced by ``test_registry_consistency``).

The data was transcribed from issue #68 (last revised 2026-05-06) and
re-validated against ``origin/main`` (2026-08-08, commit de31598). Subsequent
PRs that change command code MUST update this file in lockstep.
"""

from __future__ import annotations

from ._types import CompatEntry, CompatStatus


def _e(
    command: str,
    flag: str | None,
    status: CompatStatus,
    note: str = "",
    *,
    pending_key: str | None = None,
    unsupported_key: str | None = None,
    gc_extension: bool = False,
    aliases: tuple[str, ...] = (),
) -> CompatEntry:
    return CompatEntry(
        command=command,
        flag=flag,
        status=status,
        note=note,
        pending_key=pending_key,
        unsupported_key=unsupported_key,
        gc_extension=gc_extension,
        aliases=aliases,
    )


ENTRIES: list[CompatEntry] = [
    # --- auth subcommands ---
    _e("auth login", None, CompatStatus.IMPLEMENTED, "Supports --with-token and interactive input"),
    _e("auth logout", None, CompatStatus.IMPLEMENTED),
    _e("auth status", None, CompatStatus.IMPLEMENTED, "Simplified: token mask only"),
    _e("auth token", None, CompatStatus.IMPLEMENTED),
    # --- auth flags ---
    _e(
        "auth login",
        "--with-token",
        CompatStatus.IMPLEMENTED,
    ),
    _e("auth login", "-c/--clipboard", CompatStatus.NOT_IN_CLI),
    _e("auth login", "-p/--git-protocol", CompatStatus.NOT_IN_CLI),
    _e("auth login", "-h/--hostname", CompatStatus.NOT_IN_CLI),
    _e("auth login", "--insecure-storage", CompatStatus.NOT_IN_CLI),
    _e("auth login", "-s/--scopes", CompatStatus.NOT_IN_CLI),
    _e("auth login", "--skip-ssh-key", CompatStatus.NOT_IN_CLI),
    _e("auth login", "-w/--web", CompatStatus.NOT_IN_CLI),
    _e("auth logout", "-h/--hostname", CompatStatus.NOT_IN_CLI),
    _e("auth logout", "-u/--user", CompatStatus.NOT_IN_CLI),
    _e("auth status", "-a/--active", CompatStatus.NOT_IN_CLI),
    _e("auth status", "-h/--hostname", CompatStatus.NOT_IN_CLI),
    _e(
        "auth status",
        "--json",
        CompatStatus.PENDING,
        "Click guard added; structured output not yet implemented",
        pending_key="auth status --json",
    ),
    _e(
        "auth status",
        "--jq",
        CompatStatus.PENDING,
        "Click guard added; structured output not yet implemented",
        pending_key="auth status --jq",
    ),
    _e(
        "auth status",
        "--template",
        CompatStatus.PENDING,
        "Click guard added; structured output not yet implemented",
        pending_key="auth status --template",
    ),
    _e("auth status", "--show-token", CompatStatus.NOT_IN_CLI),
    _e("auth token", "-h/--hostname", CompatStatus.NOT_IN_CLI),
    _e("auth token", "-u/--user", CompatStatus.NOT_IN_CLI),
    # --- issue subcommands ---
    _e("issue list", None, CompatStatus.IMPLEMENTED, "Alias: ls"),
    _e("issue view", None, CompatStatus.IMPLEMENTED),
    _e("issue create", None, CompatStatus.IMPLEMENTED, "Alias: new"),
    _e("issue close", None, CompatStatus.IMPLEMENTED),
    _e("issue comment", None, CompatStatus.IMPLEMENTED),
    _e("issue reopen", None, CompatStatus.IMPLEMENTED),
    _e("issue edit", None, CompatStatus.IMPLEMENTED),
    _e(
        "issue status",
        None,
        CompatStatus.IMPLEMENTED,
        "Approximate: lacks gh user-specific filtering (ISSUE_STATUS_GH_SEMANTICS)",
    ),
    _e(
        "issue develop",
        None,
        CompatStatus.IMPLEMENTED,
        "Degraded: opens GitCode issue page, does not create/checkout local branch",
    ),
    _e(
        "issue delete",
        None,
        CompatStatus.IMPLEMENTED,
        "Uses unofficial GitCode endpoint; unstable (PR #83)",
    ),
    _e("issue lock", None, CompatStatus.NOT_IN_CLI),
    _e("issue pin", None, CompatStatus.NOT_IN_CLI),
    _e("issue transfer", None, CompatStatus.NOT_IN_CLI),
    _e("issue unlock", None, CompatStatus.NOT_IN_CLI),
    _e("issue unpin", None, CompatStatus.NOT_IN_CLI),
    # --- issue flags ---
    _e("issue list", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue list", "-s/--state", CompatStatus.IMPLEMENTED),
    _e("issue list", "-l/--label", CompatStatus.IMPLEMENTED),
    _e("issue list", "-A/--author", CompatStatus.IMPLEMENTED),
    _e("issue list", "-a/--assignee", CompatStatus.IMPLEMENTED),
    _e("issue list", "--milestone", CompatStatus.IMPLEMENTED),
    _e("issue list", "--mention", CompatStatus.IMPLEMENTED),
    _e(
        "issue list",
        "--app",
        CompatStatus.UNSUPPORTED,
        "GitCode issue API does not support application filtering",
        unsupported_key="ISSUE_LIST_APP",
    ),
    _e("issue list", "-S/--search", CompatStatus.IMPLEMENTED),
    _e("issue list", "-L/--limit", CompatStatus.IMPLEMENTED),
    _e("issue list", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("issue list", "--json", CompatStatus.IMPLEMENTED),
    _e("issue list", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e("issue list", "-t/--template", CompatStatus.IMPLEMENTED),
    _e(
        "issue list",
        "-m",
        CompatStatus.NOT_IN_CLI,
        "gh short alias clashes with gc; gc exposes --milestone only",
    ),
    _e("issue view", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue view", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("issue view", "-c/--comments", CompatStatus.IMPLEMENTED),
    _e("issue view", "--json", CompatStatus.IMPLEMENTED),
    _e("issue view", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e("issue view", "-t/--template", CompatStatus.IMPLEMENTED),
    _e("issue create", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue create", "-t/--title", CompatStatus.IMPLEMENTED),
    _e("issue create", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("issue create", "-a/--assignee", CompatStatus.IMPLEMENTED),
    _e("issue create", "-e/--editor", CompatStatus.IMPLEMENTED),
    _e("issue create", "-l/--label", CompatStatus.IMPLEMENTED),
    _e("issue create", "-m/--milestone", CompatStatus.IMPLEMENTED),
    _e("issue create", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e("issue create", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("issue create", "--json", CompatStatus.IMPLEMENTED),
    _e("issue create", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e(
        "issue create",
        "-T/--template",
        CompatStatus.IMPLEMENTED,
        "Treated as body template file (PR #91)",
    ),
    _e("issue create", "-p/--project", CompatStatus.NOT_IN_CLI, "Project association not implemented"),
    _e("issue create", "--recover", CompatStatus.NOT_IN_CLI, "Draft recovery not implemented"),
    _e("issue close", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue close", "-c/--comment", CompatStatus.IMPLEMENTED),
    _e(
        "issue close",
        "-r/--reason",
        CompatStatus.IMPLEMENTED,
        "Supports completed/not_planned; gh additionally supports duplicate",
    ),
    _e(
        "issue close",
        "--duplicate-of",
        CompatStatus.IMPLEMENTED,
        "GitCode-limited approximation: posts duplicate notice then closes (PR #89)",
    ),
    _e("issue comment", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue comment", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("issue comment", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e("issue comment", "-e/--editor", CompatStatus.IMPLEMENTED),
    _e("issue comment", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("issue comment", "--create-if-none", CompatStatus.IMPLEMENTED),
    _e("issue comment", "--delete-last", CompatStatus.IMPLEMENTED),
    _e("issue comment", "--edit-last", CompatStatus.IMPLEMENTED),
    _e("issue comment", "--yes", CompatStatus.IMPLEMENTED),
    _e("issue edit", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue edit", "-t/--title", CompatStatus.IMPLEMENTED),
    _e("issue edit", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("issue edit", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e("issue edit", "-a/--add-assignee", CompatStatus.IMPLEMENTED),
    _e("issue edit", "-l/--add-label", CompatStatus.IMPLEMENTED),
    _e("issue edit", "-m/--milestone", CompatStatus.IMPLEMENTED),
    _e("issue edit", "--remove-milestone", CompatStatus.IMPLEMENTED),
    _e("issue edit", "--remove-assignee", CompatStatus.IMPLEMENTED, "Implemented (PR #120)"),
    _e("issue edit", "--remove-label", CompatStatus.IMPLEMENTED, "Implemented (PR #120)"),
    _e("issue edit", "--add-project", CompatStatus.NOT_IN_CLI),
    _e("issue edit", "--remove-project", CompatStatus.NOT_IN_CLI),
    _e("issue reopen", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue reopen", "-c/--comment", CompatStatus.IMPLEMENTED, "Implemented (PR #122)"),
    _e("issue status", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue status", "--json", CompatStatus.IMPLEMENTED, "Implemented (PR #113)"),
    _e("issue status", "-q/--jq", CompatStatus.IMPLEMENTED, "Implemented (PR #113)"),
    _e("issue status", "-t/--template", CompatStatus.IMPLEMENTED, "Implemented (PR #113)"),
    _e("issue develop", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e(
        "issue develop",
        "-b/--base",
        CompatStatus.UNSUPPORTED,
        "GitCode API does not provide issue develop branch API",
        unsupported_key="ISSUE_DEVELOP_BASE",
    ),
    _e(
        "issue develop",
        "-n/--name",
        CompatStatus.UNSUPPORTED,
        "GitCode API does not provide issue develop branch API",
        unsupported_key="ISSUE_DEVELOP_NAME",
    ),
    _e("issue develop", "-c/--checkout", CompatStatus.NOT_IN_CLI),
    _e("issue develop", "-l/--list", CompatStatus.NOT_IN_CLI),
    _e("issue develop", "--branch-repo", CompatStatus.NOT_IN_CLI),
    _e("issue delete", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("issue delete", "--yes", CompatStatus.IMPLEMENTED),
    # --- pr subcommands ---
    _e("pr list", None, CompatStatus.IMPLEMENTED, "Alias: ls"),
    _e("pr view", None, CompatStatus.IMPLEMENTED),
    _e("pr create", None, CompatStatus.IMPLEMENTED, "Alias: new"),
    _e("pr close", None, CompatStatus.IMPLEMENTED),
    _e("pr merge", None, CompatStatus.IMPLEMENTED),
    _e("pr comment", None, CompatStatus.IMPLEMENTED),
    _e(
        "pr review",
        None,
        CompatStatus.IMPLEMENTED,
        "Degraded: --request-changes falls back to plain comment (PR_REVIEW_REQUEST_CHANGES)",
    ),
    _e("pr reopen", None, CompatStatus.IMPLEMENTED),
    _e("pr edit", None, CompatStatus.IMPLEMENTED),
    _e("pr diff", None, CompatStatus.IMPLEMENTED),
    _e("pr checkout", None, CompatStatus.IMPLEMENTED),
    _e("pr ready", None, CompatStatus.IMPLEMENTED),
    _e(
        "pr status",
        None,
        CompatStatus.IMPLEMENTED,
        "Approximate: lacks gh user-specific filtering (PR_STATUS_GH_SEMANTICS)",
    ),
    _e("pr checks", None, CompatStatus.NOT_IN_CLI),
    _e("pr lock", None, CompatStatus.NOT_IN_CLI),
    _e("pr revert", None, CompatStatus.NOT_IN_CLI),
    _e("pr unlock", None, CompatStatus.NOT_IN_CLI),
    _e("pr update-branch", None, CompatStatus.NOT_IN_CLI),
    # --- pr flags ---
    _e("pr list", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr list", "-s/--state", CompatStatus.IMPLEMENTED),
    _e("pr list", "-A/--author", CompatStatus.IMPLEMENTED),
    _e("pr list", "-B/--base", CompatStatus.IMPLEMENTED),
    _e("pr list", "-a/--assignee", CompatStatus.IMPLEMENTED),
    _e("pr list", "-d/--draft", CompatStatus.IMPLEMENTED),
    _e("pr list", "-H/--head", CompatStatus.IMPLEMENTED),
    _e("pr list", "-l/--label", CompatStatus.IMPLEMENTED),
    _e("pr list", "-S/--search", CompatStatus.IMPLEMENTED),
    _e("pr list", "-L/--limit", CompatStatus.IMPLEMENTED),
    _e("pr list", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("pr list", "--json", CompatStatus.IMPLEMENTED),
    _e("pr list", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e("pr list", "-t/--template", CompatStatus.IMPLEMENTED),
    _e("pr list", "--app", CompatStatus.NOT_IN_CLI, "App filtering not implemented"),
    _e("pr view", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr view", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("pr view", "-c/--comments", CompatStatus.IMPLEMENTED),
    _e("pr view", "--json", CompatStatus.IMPLEMENTED),
    _e("pr view", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e("pr view", "-t/--template", CompatStatus.IMPLEMENTED),
    _e("pr create", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr create", "-t/--title", CompatStatus.IMPLEMENTED),
    _e("pr create", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("pr create", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e("pr create", "-e/--editor", CompatStatus.IMPLEMENTED),
    _e("pr create", "-f/--fill", CompatStatus.IMPLEMENTED),
    _e("pr create", "--fill-first", CompatStatus.IMPLEMENTED),
    _e("pr create", "--fill-verbose", CompatStatus.IMPLEMENTED),
    _e("pr create", "--dry-run", CompatStatus.IMPLEMENTED),
    _e("pr create", "-B/--base", CompatStatus.IMPLEMENTED),
    _e("pr create", "-H/--head", CompatStatus.IMPLEMENTED),
    _e("pr create", "-d/--draft", CompatStatus.IMPLEMENTED),
    _e("pr create", "-m/--milestone", CompatStatus.IMPLEMENTED),
    _e("pr create", "-l/--label", CompatStatus.IMPLEMENTED),
    _e("pr create", "-r/--reviewer", CompatStatus.IMPLEMENTED),
    _e("pr create", "-a/--assignee", CompatStatus.IMPLEMENTED),
    _e("pr create", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("pr create", "--json", CompatStatus.IMPLEMENTED),
    _e("pr create", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e(
        "pr create",
        "-T/--template",
        CompatStatus.IMPLEMENTED,
        "Treated as body template file (PR #91)",
    ),
    _e("pr create", "-p/--project", CompatStatus.NOT_IN_CLI, "Project association not implemented"),
    _e("pr create", "--recover", CompatStatus.NOT_IN_CLI, "Draft recovery not implemented"),
    _e("pr create", "--no-maintainer-edit", CompatStatus.NOT_IN_CLI, "Maintainer-edit controls not implemented"),
    _e("pr close", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr close", "-c/--comment", CompatStatus.IMPLEMENTED),
    _e("pr close", "-d/--delete-branch", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-m/--merge", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-s/--squash", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-r/--rebase", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-d/--delete-branch", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e("pr merge", "-t/--subject", CompatStatus.IMPLEMENTED),
    _e(
        "pr merge",
        "-A/--author-email",
        CompatStatus.UNSUPPORTED,
        "GitCode merge API does not support author-email override (PR #88)",
        unsupported_key="PR_MERGE_AUTHOR_EMAIL",
    ),
    _e(
        "pr merge",
        "--auto",
        CompatStatus.UNSUPPORTED,
        "GitCode merge API does not support auto-merge/merge-queue (PR #88)",
        unsupported_key="PR_MERGE_AUTO",
    ),
    _e("pr merge", "--admin", CompatStatus.IMPLEMENTED),
    _e("pr merge", "--disable-auto", CompatStatus.NOT_IN_CLI),
    _e("pr merge", "--match-head-commit", CompatStatus.NOT_IN_CLI),
    _e("pr comment", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr comment", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("pr comment", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e("pr comment", "-e/--editor", CompatStatus.IMPLEMENTED),
    _e("pr comment", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("pr comment", "--path", CompatStatus.IMPLEMENTED, "gc extension; not in gh", gc_extension=True),
    _e("pr comment", "--position", CompatStatus.IMPLEMENTED, "gc extension; not in gh", gc_extension=True),
    _e("pr comment", "--line", CompatStatus.IMPLEMENTED, "gc extension; not in gh", gc_extension=True),
    _e("pr comment", "--side", CompatStatus.IMPLEMENTED, "gc extension; not in gh", gc_extension=True),
    _e("pr comment", "--commit-id", CompatStatus.IMPLEMENTED, "gc extension; not in gh", gc_extension=True),
    _e(
        "pr comment",
        "--create-if-none",
        CompatStatus.PENDING,
        "Click guard added; history management not yet implemented",
        pending_key="pr comment --create-if-none",
    ),
    _e(
        "pr comment",
        "--delete-last",
        CompatStatus.PENDING,
        "Click guard added; history management not yet implemented",
        pending_key="pr comment --delete-last",
    ),
    _e(
        "pr comment",
        "--edit-last",
        CompatStatus.PENDING,
        "Click guard added; history management not yet implemented",
        pending_key="pr comment --edit-last",
    ),
    _e(
        "pr comment",
        "--yes",
        CompatStatus.PENDING,
        "Click guard added; confirmation skip not yet implemented",
        pending_key="pr comment --yes",
    ),
    _e("pr review", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr review", "-a/--approve", CompatStatus.IMPLEMENTED),
    _e("pr review", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("pr review", "-c/--comment", CompatStatus.IMPLEMENTED),
    _e(
        "pr review",
        "-r/--request-changes",
        CompatStatus.IMPLEMENTED,
        "Degraded: posts plain comment (PR_REVIEW_REQUEST_CHANGES)",
    ),
    _e("pr review", "--force", CompatStatus.IMPLEMENTED, "gc extension", gc_extension=True),
    _e("pr review", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e("pr reopen", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e(
        "pr reopen",
        "-c/--comment",
        CompatStatus.PENDING,
        "Click guard added; gh supports reopening with comment",
        pending_key="pr reopen --comment",
    ),
    _e("pr edit", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr edit", "-t/--title", CompatStatus.IMPLEMENTED),
    _e("pr edit", "-b/--body", CompatStatus.IMPLEMENTED),
    _e("pr edit", "-F/--body-file", CompatStatus.IMPLEMENTED),
    _e(
        "pr edit",
        "-B/--base",
        CompatStatus.UNSUPPORTED,
        "GitCode PR update API does not support base branch changes (PR #137)",
        unsupported_key="PR_EDIT_BASE",
    ),
    _e("pr edit", "-a/--add-assignee", CompatStatus.IMPLEMENTED),
    _e("pr edit", "-l/--add-label", CompatStatus.IMPLEMENTED),
    _e("pr edit", "-r/--add-reviewer", CompatStatus.IMPLEMENTED),
    _e("pr edit", "--remove-assignee", CompatStatus.IMPLEMENTED),
    _e("pr edit", "--remove-label", CompatStatus.IMPLEMENTED),
    _e("pr edit", "--remove-reviewer", CompatStatus.IMPLEMENTED),
    _e("pr edit", "-m/--milestone", CompatStatus.IMPLEMENTED),
    _e("pr edit", "--remove-milestone", CompatStatus.IMPLEMENTED),
    _e("pr edit", "--add-project", CompatStatus.NOT_IN_CLI),
    _e("pr edit", "--remove-project", CompatStatus.NOT_IN_CLI),
    _e("pr diff", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr diff", "--color", CompatStatus.NOT_IN_CLI),
    _e("pr diff", "-e/--exclude", CompatStatus.NOT_IN_CLI),
    _e(
        "pr diff",
        "--name-only",
        CompatStatus.PENDING,
        "Click guard added; behaviour not yet implemented",
        pending_key="pr diff --name-only",
    ),
    _e(
        "pr diff",
        "--patch",
        CompatStatus.PENDING,
        "Click guard added; behaviour not yet implemented",
        pending_key="pr diff --patch",
    ),
    _e("pr diff", "-w/--web", CompatStatus.NOT_IN_CLI),
    _e("pr checkout", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr checkout", "-b/--branch", CompatStatus.IMPLEMENTED),
    _e(
        "pr checkout",
        "--detach",
        CompatStatus.PENDING,
        "Click guard added; behaviour not yet implemented",
        pending_key="pr checkout --detach",
    ),
    _e(
        "pr checkout",
        "-f/--force",
        CompatStatus.PENDING,
        "Click guard added; behaviour not yet implemented",
        pending_key="pr checkout --force",
    ),
    _e("pr checkout", "--recurse-submodules", CompatStatus.NOT_IN_CLI),
    _e("pr ready", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr ready", "--undo", CompatStatus.IMPLEMENTED),
    _e("pr status", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("pr status", "-c/--conflict-status", CompatStatus.NOT_IN_CLI),
    _e("pr status", "--json", CompatStatus.NOT_IN_CLI),
    _e("pr status", "-q/--jq", CompatStatus.NOT_IN_CLI),
    _e("pr status", "-t/--template", CompatStatus.NOT_IN_CLI),
    # --- repo subcommands ---
    _e("repo view", None, CompatStatus.IMPLEMENTED, "Repository positional or -R/origin resolution"),
    _e("repo list", None, CompatStatus.IMPLEMENTED, "Owner argument defaults to the authenticated user"),
    _e("repo create", None, CompatStatus.IMPLEMENTED, "OWNER/NAME creates via POST /orgs/{org}/repos"),
    _e("repo clone", None, CompatStatus.IMPLEMENTED, "Executes git clone against gitcode.com"),
    _e("repo fork", None, CompatStatus.IMPLEMENTED),
    _e("repo edit", None, CompatStatus.IMPLEMENTED),
    _e("repo rename", None, CompatStatus.IMPLEMENTED, "Best-effort origin remote URL update"),
    _e("repo delete", None, CompatStatus.IMPLEMENTED, "Confirmation prompt unless --yes"),
    _e(
        "repo sync",
        None,
        CompatStatus.IMPLEMENTED,
        "Fork-sync only, via PUT /repos/{owner}/{repo}/sync_repo; branch/source selection not available",
    ),
    _e(
        "repo archive",
        None,
        CompatStatus.NOT_IN_CLI,
        "GitCode documents an org-scoped archive endpoint (PUT /api/v5/org/{org}/repo/{repo}/status)"
        " without documented request parameters",
    ),
    _e(
        "repo unarchive",
        None,
        CompatStatus.NOT_IN_CLI,
        "GitCode documents no unarchive endpoint",
    ),
    _e(
        "repo deploy-key",
        None,
        CompatStatus.NOT_IN_CLI,
        "No GitCode v5 deploy-key equivalent (only account-level /user/keys exists)",
    ),
    _e(
        "repo set-default",
        None,
        CompatStatus.NOT_IN_CLI,
        "gc resolves repositories from the git origin remote instead of a per-directory default",
    ),
    _e("repo autolink", None, CompatStatus.NOT_IN_CLI),
    _e("repo gitignore", None, CompatStatus.NOT_IN_CLI),
    _e("repo license", None, CompatStatus.NOT_IN_CLI),
    # --- repo flags ---
    _e(
        "repo view",
        "-R/--repo",
        CompatStatus.IMPLEMENTED,
        "gc extension; gh repo view uses the repository positional",
        gc_extension=True,
    ),
    _e("repo view", "-w/--web", CompatStatus.IMPLEMENTED),
    _e("repo view", "--json", CompatStatus.IMPLEMENTED),
    _e("repo view", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e("repo view", "-t/--template", CompatStatus.IMPLEMENTED),
    _e("repo view", "-b/--branch", CompatStatus.NOT_IN_CLI, "Per-branch README selection not implemented"),
    _e("repo list", "-L/--limit", CompatStatus.IMPLEMENTED),
    _e("repo list", "--json", CompatStatus.IMPLEMENTED),
    _e("repo list", "-q/--jq", CompatStatus.IMPLEMENTED),
    _e("repo list", "-t/--template", CompatStatus.IMPLEMENTED),
    _e("repo list", "--visibility", CompatStatus.IMPLEMENTED, "Client-side filter"),
    _e("repo list", "-l/--language", CompatStatus.IMPLEMENTED, "Client-side filter"),
    _e("repo list", "--fork", CompatStatus.IMPLEMENTED, "Client-side filter"),
    _e("repo list", "--source", CompatStatus.IMPLEMENTED, "Client-side filter (non-forks)"),
    _e(
        "repo list",
        "--archived",
        CompatStatus.NOT_IN_CLI,
        "GitCode does not expose archive state reliably in list responses",
    ),
    _e(
        "repo list",
        "--no-archived",
        CompatStatus.NOT_IN_CLI,
        "GitCode does not expose archive state reliably in list responses",
    ),
    _e("repo list", "--topic", CompatStatus.NOT_IN_CLI, "GitCode v5 has no repository topics API"),
    _e("repo create", "-d/--description", CompatStatus.IMPLEMENTED),
    _e("repo create", "--add-readme", CompatStatus.IMPLEMENTED, "Maps to auto_init"),
    _e("repo create", "--public", CompatStatus.IMPLEMENTED),
    _e("repo create", "--private", CompatStatus.IMPLEMENTED, "Default when no visibility flag is given"),
    _e(
        "repo create",
        "--internal",
        CompatStatus.UNSUPPORTED,
        "GitCode repositories are either public or private",
        unsupported_key="REPO_CREATE_INTERNAL",
    ),
    _e("repo create", "--homepage", CompatStatus.IMPLEMENTED, "The gh -h short flag is reserved for help in gc"),
    _e("repo create", "--disable-issues", CompatStatus.IMPLEMENTED, "Maps to has_issues=false"),
    _e("repo create", "--disable-wiki", CompatStatus.IMPLEMENTED, "Maps to has_wiki=false"),
    _e("repo create", "-g/--gitignore", CompatStatus.IMPLEMENTED, "Maps to gitignore_template"),
    _e("repo create", "-l/--license", CompatStatus.IMPLEMENTED, "Maps to license_template"),
    _e("repo create", "-c/--clone", CompatStatus.IMPLEMENTED),
    _e("repo create", "-s/--source", CompatStatus.NOT_IN_CLI, "Local-repository push flows not implemented"),
    _e("repo create", "--push", CompatStatus.NOT_IN_CLI, "Local-repository push flows not implemented"),
    _e("repo create", "-r/--remote", CompatStatus.NOT_IN_CLI, "Depends on --source, which is not implemented"),
    _e("repo create", "-t/--team", CompatStatus.NOT_IN_CLI, "Team access grants have no GitCode v5 equivalent"),
    _e("repo create", "-p/--template", CompatStatus.NOT_IN_CLI, "Template repositories have no GitCode v5 equivalent"),
    _e(
        "repo create",
        "--include-all-branches",
        CompatStatus.NOT_IN_CLI,
        "Template repositories have no GitCode v5 equivalent",
    ),
    _e("repo clone", "--no-upstream", CompatStatus.NOT_IN_CLI, "Upstream remote management not implemented"),
    _e(
        "repo clone", "-u/--upstream-remote-name", CompatStatus.NOT_IN_CLI, "Upstream remote management not implemented"
    ),
    _e(
        "repo fork",
        "-R/--repo",
        CompatStatus.IMPLEMENTED,
        "gc extension; gh repo fork uses the repository positional",
        gc_extension=True,
    ),
    _e("repo fork", "--clone", CompatStatus.IMPLEMENTED),
    _e("repo fork", "--org", CompatStatus.IMPLEMENTED, "Maps to the fork API org parameter"),
    _e(
        "repo fork",
        "--fork-name",
        CompatStatus.UNSUPPORTED,
        "GitCode fork API cannot rename the fork during creation",
        unsupported_key="REPO_FORK_NAME",
    ),
    _e(
        "repo fork",
        "--default-branch-only",
        CompatStatus.UNSUPPORTED,
        "GitCode forks always copy every branch",
        unsupported_key="REPO_FORK_DEFAULT_BRANCH_ONLY",
    ),
    _e("repo fork", "--remote", CompatStatus.NOT_IN_CLI, "Local remote rewiring not implemented"),
    _e("repo fork", "--remote-name", CompatStatus.NOT_IN_CLI, "Local remote rewiring not implemented"),
    _e(
        "repo edit",
        "-R/--repo",
        CompatStatus.IMPLEMENTED,
        "gc extension; gh repo edit uses the repository positional",
        gc_extension=True,
    ),
    _e("repo edit", "-d/--description", CompatStatus.IMPLEMENTED),
    _e("repo edit", "--homepage", CompatStatus.IMPLEMENTED, "The gh -h short flag is reserved for help in gc"),
    _e("repo edit", "--default-branch", CompatStatus.IMPLEMENTED),
    _e(
        "repo edit", "--visibility", CompatStatus.IMPLEMENTED, "public/private only; GitCode has no internal visibility"
    ),
    _e("repo edit", "--enable-issues", CompatStatus.IMPLEMENTED, "Pairs with --disable-issues via has_issues"),
    _e("repo edit", "--enable-wiki", CompatStatus.IMPLEMENTED, "Pairs with --disable-wiki via has_wiki"),
    _e("repo edit", "--add-topic", CompatStatus.NOT_IN_CLI, "GitCode v5 has no repository topics API"),
    _e("repo edit", "--remove-topic", CompatStatus.NOT_IN_CLI, "GitCode v5 has no repository topics API"),
    _e("repo edit", "--accept-visibility-change-consequences", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--allow-forking", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--allow-update-branch", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--delete-branch-on-merge", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-advanced-security", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-auto-merge", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-discussions", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-merge-commit", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-projects", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-rebase-merge", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-secret-scanning", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-secret-scanning-push-protection", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--enable-squash-merge", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--squash-merge-commit-message", CompatStatus.NOT_IN_CLI),
    _e("repo edit", "--template", CompatStatus.NOT_IN_CLI),
    _e("repo rename", "-R/--repo", CompatStatus.IMPLEMENTED),
    _e("repo rename", "-y/--yes", CompatStatus.IMPLEMENTED),
    _e(
        "repo delete",
        "-R/--repo",
        CompatStatus.IMPLEMENTED,
        "gc extension; gh repo delete uses the repository positional",
        gc_extension=True,
    ),
    _e("repo delete", "--yes", CompatStatus.IMPLEMENTED),
    _e(
        "repo sync",
        "-R/--repo",
        CompatStatus.IMPLEMENTED,
        "gc extension; gh repo sync uses the repository positional",
        gc_extension=True,
    ),
    _e("repo sync", "-b/--branch", CompatStatus.NOT_IN_CLI, "GitCode fork sync has no branch selection"),
    _e("repo sync", "--force", CompatStatus.NOT_IN_CLI, "GitCode fork sync has no force mode"),
    _e("repo sync", "-s/--source", CompatStatus.NOT_IN_CLI, "GitCode fork sync always uses the upstream parent"),
]
